// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzscm6TwLgfbKSHZt_2PqWvHlQ5pKymIY',
    appId: '1:884257635300:android:efb7af0bc91969e2ece5f1',
    messagingSenderId: '884257635300',
    projectId: 'oddo-emotion-diary',
    storageBucket: 'oddo-emotion-diary.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASrNTIjCy62gOZWXBEqpnkii5_utbtO9I',
    appId: '1:884257635300:ios:21c1b972535b70c1ece5f1',
    messagingSenderId: '884257635300',
    projectId: 'oddo-emotion-diary',
    storageBucket: 'oddo-emotion-diary.firebasestorage.app',
    androidClientId: '884257635300-fbbfv2tvsg38br2qvt00otrc55km1k9c.apps.googleusercontent.com',
    iosClientId: '884257635300-t0tmj7lrm8lcsf76ovcbjmdd06okgd3j.apps.googleusercontent.com',
    iosBundleId: 'app.oddo.oddo',
  );
}
